const { chromium } = require('playwright');
(async()=>{
  const b=await chromium.launch({args:['--use-angle=swiftshader','--enable-unsafe-swiftshader','--no-proxy-server']});
  const ctx=await b.newContext({viewport:{width:1100,height:700}});
  const errs=[];
  await ctx.route(/fonts\.(googleapis|gstatic)\.com/,r=>r.abort());
  const A=await ctx.newPage(),B=await ctx.newPage();
  for(const [n,p] of [['A',A],['B',B]]){p.on('pageerror',e=>errs.push(n+':'+e.message));const s=await ctx.newCDPSession(p);await s.send('Emulation.setFocusEmulationEnabled',{enabled:true});}
  await A.goto('http://127.0.0.1:8765/test_mp.html',{waitUntil:'commit'});
  await B.goto('http://127.0.0.1:8765/test_mp.html',{waitUntil:'commit'});
  await A.waitForTimeout(12000);
  for(const p of [A,B])await p.evaluate(()=>{document.querySelector('#cTop').click();});
  await A.click('#bHostPub');await A.waitForTimeout(2000);
  await A.screenshot({path:'mp1-host-lobby.png'});
  await B.waitForTimeout(1500);await B.screenshot({path:'mp2-guest-menu.png'});
  const list=await B.evaluate(()=>document.querySelector('#roomList').innerText);console.log('B sees rooms:',JSON.stringify(list));
  await B.click('.roomcard');await B.waitForTimeout(2000);
  await B.click('#lobbyTyre button[data-t="S"]');await B.click('#bReady');await B.waitForTimeout(1500);
  await A.screenshot({path:'mp3-host-lobby2.png'});
  await A.selectOption('#lAi','3');await A.waitForTimeout(500);
  await A.click('#bStartOnline');
  const drive=async(sec)=>{const end=Date.now()+sec*1000;while(Date.now()<end){await Promise.all([A.evaluate(()=>window.__T.frame(performance.now(),true)),B.evaluate(()=>window.__T.frame(performance.now(),true))]);await A.waitForTimeout(40);}};
  await drive(12);
  const snap=async p=>p.evaluate(()=>{const T=window.__T;return {started:T.G.started,time:T.G.time.toFixed(2),N:T.G.neutral&&T.G.neutral.type,cars:T.G.cars.map(c=>[c.code,c.kin?'kin':c.ai?'ai':'me',c.pf.toFixed(1),Math.round(c.x),Math.round(c.y),c.tyre])}});
  const a1=await snap(A),b1=await snap(B);console.log('A',JSON.stringify(a1));console.log('B',JSON.stringify(b1));
  for(const p of [A,B])await p.evaluate(()=>{const pl=window.__T.G.player;pl.ai=true;pl.skill=.9;});
  await drive(20);
  const a2=await snap(A),b2=await snap(B);console.log('A2',JSON.stringify(a2));console.log('B2',JSON.stringify(b2));
  await A.evaluate(()=>window.__T.deploySC());await drive(8);
  const a3=await snap(A),b3=await snap(B);console.log('A3',JSON.stringify(a3));console.log('B3',JSON.stringify(b3));
  await B.screenshot({path:'mp4-guest-race.png'});
  console.log('errors',errs.slice(0,5));
  await b.close();
  // checks: guest saw the room, both clients agree on the race, the SC reached the guest, no page errors
  const fails=[],ck=(ok,msg)=>{if(!ok)fails.push(msg);};
  ck(/JOIN/.test(list),'guest did not see the public room');
  for(const [n,s] of [['A',a1],['B',b1],['A2',a2],['B2',b2],['A3',a3],['B3',b3]])ck(s.started,n+': race not started');
  for(const [n,s] of [['start',[a1,b1]],['mid',[a2,b2]],['SC',[a3,b3]]])ck(s[0].cars.length===5&&s[1].cars.length===5,n+': expected 5 cars on both clients, got '+s[0].cars.length+' and '+s[1].cars.length);
  ck(a1.cars.filter(c=>c[1]==='kin').length===1,'host should see exactly one remote car');
  ck(b1.cars.filter(c=>c[1]==='kin').length===4,'guest should see four remote cars');
  const hostView=a1.cars.find(c=>c[1]==='kin'),guestView=b1.cars.find(c=>c[0]==='YOU');
  ck(hostView&&guestView&&hostView[5]==='S'&&guestView[5]==='S','guest car should start on the Soft it picked in the lobby');
  const pf=(s,code)=>+s.cars.find(c=>c[0]===code)[2],ai=a1.cars.filter(c=>c[1]==='ai').map(c=>c[0]);
  ck(ai.length===3,'host should run three AI cars, got '+ai.length);
  for(const code of ai)ck(pf(a2,code)>pf(a1,code)+100&&pf(b2,code)>pf(b1,code)+100,code+' did not make progress on both clients');
  for(const code of ai)ck(Math.abs(pf(a2,code)-pf(b2,code))<30,code+' position differs between clients: '+pf(a2,code)+' vs '+pf(b2,code));
  ck(a3.N==='SC'&&b3.N==='SC','safety car not active on both clients: '+a3.N+' / '+b3.N);
  for(const e of errs)fails.push('page error: '+e);
  if(fails.length){console.error('FAIL\n  '+fails.join('\n  '));process.exit(1);}
  console.log('PASS');
})().catch(e=>{console.error(e);process.exit(1);});
